### ISSUE TITLE
Надо сосчитать общий бонус - сколько менеджер получит всего денег

### ISSUE THREAD

**Issue by coursar** [jafarsirojov/bonuse#2]
https://github.com/jafarsirojov/bonuse/blob/6706fb41a4fca4ed7c01289a83711a56cdada8c8/main.go#L6-L10

**Comment by jafarsirojov** [comment]
@coursar, Готово!
 func main() {
	sales := []int{12_000,8_000,15_000,8_000}
	result :=0
	for _, sale := range sales{
		result += bonuses(sale)
	}

}
